// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pb/v2/commonpb/base_where.proto

package common

import (
	fmt "fmt"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"

	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/gogo/protobuf/types"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	golang_proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = golang_proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type BaseWhere struct {
	SearchIn             string     `protobuf:"bytes,1,opt,name=search_in,json=searchIn,proto3" json:"search_in,omitempty"`
	Keyword              string     `protobuf:"bytes,2,opt,name=keyword,proto3" json:"keyword,omitempty"`
	CreatedAtLt          *time.Time `protobuf:"bytes,3,opt,name=created_at_lt,json=createdAtLt,proto3,stdtime" json:"created_at_lt,omitempty" gorm:"column:created_at_lt; default:DATE('1970-01-01 00:00:00')"`
	CreatedAtLte         *time.Time `protobuf:"bytes,4,opt,name=created_at_lte,json=createdAtLte,proto3,stdtime" json:"created_at_lte,omitempty" gorm:"column:created_at_lte; default:DATE('1970-01-01 00:00:00')"`
	CreatedAtGt          *time.Time `protobuf:"bytes,5,opt,name=created_at_gt,json=createdAtGt,proto3,stdtime" json:"created_at_gt,omitempty" gorm:"column:created_at_gt; default:DATE('1970-01-01 00:00:00')"`
	CreatedAtGte         *time.Time `protobuf:"bytes,6,opt,name=created_at_gte,json=createdAtGte,proto3,stdtime" json:"created_at_gte,omitempty" gorm:"column:created_at_gte; default:DATE('1970-01-01 00:00:00')"`
	UpdatedAtLt          *time.Time `protobuf:"bytes,8,opt,name=updated_at_lt,json=updatedAtLt,proto3,stdtime" json:"updated_at_lt,omitempty" gorm:"column:updated_at_lt; default:DATE('1970-01-01 00:00:00')"`
	UpdatedAtLte         *time.Time `protobuf:"bytes,9,opt,name=updated_at_lte,json=updatedAtLte,proto3,stdtime" json:"updated_at_lte,omitempty" gorm:"column:updated_at_lte; default:DATE('1970-01-01 00:00:00')"`
	UpdatedAtGt          *time.Time `protobuf:"bytes,10,opt,name=updated_at_gt,json=updatedAtGt,proto3,stdtime" json:"updated_at_gt,omitempty" gorm:"column:updated_at_gt; default:DATE('1970-01-01 00:00:00')"`
	UpdatedAtGte         *time.Time `protobuf:"bytes,11,opt,name=updated_at_gte,json=updatedAtGte,proto3,stdtime" json:"updated_at_gte,omitempty" gorm:"column:updated_at_gte; default:DATE('1970-01-01 00:00:00')"`
	IDs                  []int64    `protobuf:"varint,12,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	CreatorID            int64      `protobuf:"varint,13,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	CreatorName          string     `protobuf:"bytes,14,opt,name=creator_name,json=creatorName,proto3" json:"creator_name,omitempty"`
	UpdaterID            int64      `protobuf:"varint,15,opt,name=updater_id,json=updaterId,proto3" json:"updater_id,omitempty"`
	UpdaterName          string     `protobuf:"bytes,16,opt,name=updater_name,json=updaterName,proto3" json:"updater_name,omitempty"`
	DeletedAtLt          *time.Time `protobuf:"bytes,17,opt,name=deleted_at_lt,json=deletedAtLt,proto3,stdtime" json:"deleted_at_lt,omitempty" gorm:"column:deleted_at_lt; default:DATE('1970-01-01 00:00:00')"`
	DeletedAtLte         *time.Time `protobuf:"bytes,18,opt,name=deleted_at_lte,json=deletedAtLte,proto3,stdtime" json:"deleted_at_lte,omitempty" gorm:"column:deleted_at_lte; default:DATE('1970-01-01 00:00:00')"`
	DeletedAtGt          *time.Time `protobuf:"bytes,19,opt,name=deleted_at_gt,json=deletedAtGt,proto3,stdtime" json:"deleted_at_gt,omitempty" gorm:"column:deleted_at_gt; default:DATE('1970-01-01 00:00:00')"`
	DeletedAtGte         *time.Time `protobuf:"bytes,20,opt,name=deleted_at_gte,json=deletedAtGte,proto3,stdtime" json:"deleted_at_gte,omitempty" gorm:"column:deleted_at_gte; default:DATE('1970-01-01 00:00:00')"`
	ExpiredAtGt          *time.Time `protobuf:"bytes,21,opt,name=expired_at_gt,json=expiredAtGt,proto3,stdtime" json:"expired_at_gt,omitempty" gorm:"column:expired_at_gt; default:DATE('1970-01-01 00:00:00')"`
	ExpiredAtGte         *time.Time `protobuf:"bytes,22,opt,name=expired_at_gte,json=expiredAtGte,proto3,stdtime" json:"expired_at_gte,omitempty" gorm:"column:expired_at_gte; default:DATE('1970-01-01 00:00:00')"`
	ExpiredAtLt          *time.Time `protobuf:"bytes,23,opt,name=expired_at_lt,json=expiredAtLt,proto3,stdtime" json:"expired_at_lt,omitempty" gorm:"column:expired_at_lt; default:DATE('1970-01-01 00:00:00')"`
	ExpiredAtLte         *time.Time `protobuf:"bytes,24,opt,name=expired_at_lte,json=expiredAtLte,proto3,stdtime" json:"expired_at_lte,omitempty" gorm:"column:expired_at_lte; default:DATE('1970-01-01 00:00:00')"`
	CompletedAtLt        *time.Time `protobuf:"bytes,25,opt,name=completed_at_lt,json=completedAtLt,proto3,stdtime" json:"completed_at_lt,omitempty" gorm:"column:completed_at_lt; default:DATE('1970-01-01 00:00:00')"`
	CompletedAtLte       *time.Time `protobuf:"bytes,26,opt,name=completed_at_lte,json=completedAtLte,proto3,stdtime" json:"completed_at_lte,omitempty" gorm:"column:completed_at_lte; default:DATE('1970-01-01 00:00:00')"`
	CompletedAtGt        *time.Time `protobuf:"bytes,27,opt,name=completed_at_gt,json=completedAtGt,proto3,stdtime" json:"completed_at_gt,omitempty" gorm:"column:completed_at_gt; default:DATE('1970-01-01 00:00:00')"`
	CompletedAtGte       *time.Time `protobuf:"bytes,28,opt,name=completed_at_gte,json=completedAtGte,proto3,stdtime" json:"completed_at_gte,omitempty" gorm:"column:completed_at_gte; default:DATE('1970-01-01 00:00:00')"`
	TradeTimeGt          *time.Time `protobuf:"bytes,29,opt,name=trade_time_gt,json=tradeTimeGt,proto3,stdtime" json:"trade_time_gt,omitempty" default:DATE('1970-01-01 00:00:00')"`
	TradeTimeGte         *time.Time `protobuf:"bytes,30,opt,name=trade_time_gte,json=tradeTimeGte,proto3,stdtime" json:"trade_time_gte,omitempty" default:DATE('1970-01-01 00:00:00')"`
	TradeTimeLt          *time.Time `protobuf:"bytes,31,opt,name=trade_time_lt,json=tradeTimeLt,proto3,stdtime" json:"trade_time_lt,omitempty" default:DATE('1970-01-01 00:00:00')"`
	TradeTimeLte         *time.Time `protobuf:"bytes,32,opt,name=trade_time_lte,json=tradeTimeLte,proto3,stdtime" json:"trade_time_lte,omitempty" default:DATE('1970-01-01 00:00:00')"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *BaseWhere) Reset()         { *m = BaseWhere{} }
func (m *BaseWhere) String() string { return proto.CompactTextString(m) }
func (*BaseWhere) ProtoMessage()    {}
func (*BaseWhere) Descriptor() ([]byte, []int) {
	return fileDescriptor_c48bce21e4357548, []int{0}
}
func (m *BaseWhere) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BaseWhere) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BaseWhere.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BaseWhere) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseWhere.Merge(m, src)
}
func (m *BaseWhere) XXX_Size() int {
	return m.Size()
}
func (m *BaseWhere) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseWhere.DiscardUnknown(m)
}

var xxx_messageInfo_BaseWhere proto.InternalMessageInfo

func (m *BaseWhere) GetSearchIn() string {
	if m != nil {
		return m.SearchIn
	}
	return ""
}

func (m *BaseWhere) GetKeyword() string {
	if m != nil {
		return m.Keyword
	}
	return ""
}

func (m *BaseWhere) GetCreatedAtLt() *time.Time {
	if m != nil {
		return m.CreatedAtLt
	}
	return nil
}

func (m *BaseWhere) GetCreatedAtLte() *time.Time {
	if m != nil {
		return m.CreatedAtLte
	}
	return nil
}

func (m *BaseWhere) GetCreatedAtGt() *time.Time {
	if m != nil {
		return m.CreatedAtGt
	}
	return nil
}

func (m *BaseWhere) GetCreatedAtGte() *time.Time {
	if m != nil {
		return m.CreatedAtGte
	}
	return nil
}

func (m *BaseWhere) GetUpdatedAtLt() *time.Time {
	if m != nil {
		return m.UpdatedAtLt
	}
	return nil
}

func (m *BaseWhere) GetUpdatedAtLte() *time.Time {
	if m != nil {
		return m.UpdatedAtLte
	}
	return nil
}

func (m *BaseWhere) GetUpdatedAtGt() *time.Time {
	if m != nil {
		return m.UpdatedAtGt
	}
	return nil
}

func (m *BaseWhere) GetUpdatedAtGte() *time.Time {
	if m != nil {
		return m.UpdatedAtGte
	}
	return nil
}

func (m *BaseWhere) GetIDs() []int64 {
	if m != nil {
		return m.IDs
	}
	return nil
}

func (m *BaseWhere) GetCreatorID() int64 {
	if m != nil {
		return m.CreatorID
	}
	return 0
}

func (m *BaseWhere) GetCreatorName() string {
	if m != nil {
		return m.CreatorName
	}
	return ""
}

func (m *BaseWhere) GetUpdaterID() int64 {
	if m != nil {
		return m.UpdaterID
	}
	return 0
}

func (m *BaseWhere) GetUpdaterName() string {
	if m != nil {
		return m.UpdaterName
	}
	return ""
}

func (m *BaseWhere) GetDeletedAtLt() *time.Time {
	if m != nil {
		return m.DeletedAtLt
	}
	return nil
}

func (m *BaseWhere) GetDeletedAtLte() *time.Time {
	if m != nil {
		return m.DeletedAtLte
	}
	return nil
}

func (m *BaseWhere) GetDeletedAtGt() *time.Time {
	if m != nil {
		return m.DeletedAtGt
	}
	return nil
}

func (m *BaseWhere) GetDeletedAtGte() *time.Time {
	if m != nil {
		return m.DeletedAtGte
	}
	return nil
}

func (m *BaseWhere) GetExpiredAtGt() *time.Time {
	if m != nil {
		return m.ExpiredAtGt
	}
	return nil
}

func (m *BaseWhere) GetExpiredAtGte() *time.Time {
	if m != nil {
		return m.ExpiredAtGte
	}
	return nil
}

func (m *BaseWhere) GetExpiredAtLt() *time.Time {
	if m != nil {
		return m.ExpiredAtLt
	}
	return nil
}

func (m *BaseWhere) GetExpiredAtLte() *time.Time {
	if m != nil {
		return m.ExpiredAtLte
	}
	return nil
}

func (m *BaseWhere) GetCompletedAtLt() *time.Time {
	if m != nil {
		return m.CompletedAtLt
	}
	return nil
}

func (m *BaseWhere) GetCompletedAtLte() *time.Time {
	if m != nil {
		return m.CompletedAtLte
	}
	return nil
}

func (m *BaseWhere) GetCompletedAtGt() *time.Time {
	if m != nil {
		return m.CompletedAtGt
	}
	return nil
}

func (m *BaseWhere) GetCompletedAtGte() *time.Time {
	if m != nil {
		return m.CompletedAtGte
	}
	return nil
}

func (m *BaseWhere) GetTradeTimeGt() *time.Time {
	if m != nil {
		return m.TradeTimeGt
	}
	return nil
}

func (m *BaseWhere) GetTradeTimeGte() *time.Time {
	if m != nil {
		return m.TradeTimeGte
	}
	return nil
}

func (m *BaseWhere) GetTradeTimeLt() *time.Time {
	if m != nil {
		return m.TradeTimeLt
	}
	return nil
}

func (m *BaseWhere) GetTradeTimeLte() *time.Time {
	if m != nil {
		return m.TradeTimeLte
	}
	return nil
}

func init() {
	proto.RegisterType((*BaseWhere)(nil), "commonpbv2.BaseWhere")
	golang_proto.RegisterType((*BaseWhere)(nil), "commonpbv2.BaseWhere")
}

func init() { proto.RegisterFile("pb/v2/commonpb/base_where.proto", fileDescriptor_c48bce21e4357548) }
func init() {
	golang_proto.RegisterFile("pb/v2/commonpb/base_where.proto", fileDescriptor_c48bce21e4357548)
}

var fileDescriptor_c48bce21e4357548 = []byte{
	// 811 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x97, 0xdd, 0x4e, 0xdb, 0x48,
	0x14, 0xc7, 0xe5, 0xcd, 0x2e, 0x90, 0xc9, 0x07, 0xac, 0xf7, 0x6b, 0x08, 0x6c, 0x9c, 0x45, 0x2b,
	0x91, 0x95, 0x96, 0x38, 0xc0, 0x45, 0xd5, 0xf4, 0xa6, 0x04, 0x50, 0x14, 0x29, 0xa5, 0x52, 0x44,
	0x55, 0xa9, 0x37, 0x91, 0x13, 0x1f, 0x26, 0x16, 0x76, 0xc6, 0x72, 0x26, 0xd0, 0xbe, 0x43, 0xa5,
	0x56, 0x95, 0xfa, 0x18, 0x7d, 0x87, 0x5e, 0x72, 0xd9, 0x27, 0x48, 0xab, 0xf4, 0x0d, 0xfa, 0x04,
	0xd5, 0xd8, 0x4e, 0xc8, 0x24, 0xb4, 0xa9, 0xc7, 0x20, 0x71, 0x81, 0x8f, 0xcf, 0xfc, 0xcf, 0x7f,
	0x7e, 0x73, 0x8e, 0x95, 0x41, 0x9a, 0xdb, 0xd6, 0x2f, 0xf6, 0xf4, 0x0e, 0x75, 0x1c, 0xda, 0x73,
	0xdb, 0x7a, 0xdb, 0xe8, 0x43, 0xeb, 0xb2, 0x0b, 0x1e, 0x94, 0x5c, 0x8f, 0x32, 0xaa, 0xa2, 0xf1,
	0xab, 0x8b, 0xbd, 0x9c, 0x46, 0x28, 0x25, 0x36, 0xe8, 0xfe, 0x9b, 0xf6, 0xe0, 0x4c, 0x67, 0x96,
	0x03, 0x7d, 0x66, 0x38, 0x6e, 0x90, 0x9c, 0xdb, 0x21, 0x16, 0xeb, 0x0e, 0xda, 0xa5, 0x0e, 0x75,
	0x74, 0x42, 0x09, 0xbd, 0xce, 0xe4, 0x4f, 0xfe, 0x83, 0xff, 0x5f, 0x90, 0xbe, 0xf5, 0x6e, 0x13,
	0x25, 0xab, 0x46, 0x1f, 0x9e, 0xf2, 0x7a, 0xea, 0x06, 0x4a, 0xf6, 0xc1, 0xf0, 0x3a, 0xdd, 0x96,
	0xd5, 0xc3, 0x4a, 0x41, 0x29, 0x26, 0x9b, 0x2b, 0x41, 0xa0, 0xde, 0x53, 0x31, 0x5a, 0x3e, 0x87,
	0x17, 0x97, 0xd4, 0x33, 0xf1, 0x4f, 0xfe, 0xab, 0xf1, 0xa3, 0xfa, 0x52, 0x41, 0x99, 0x8e, 0x07,
	0x06, 0x03, 0xb3, 0x65, 0xb0, 0x96, 0xcd, 0x70, 0xa2, 0xa0, 0x14, 0x53, 0x7b, 0xb9, 0x52, 0xe0,
	0xb6, 0x34, 0xf6, 0x50, 0x3a, 0x1d, 0xbb, 0xad, 0x36, 0xae, 0x86, 0x9a, 0xf2, 0x65, 0xa8, 0x3d,
	0x24, 0xd4, 0x73, 0x2a, 0x5b, 0x1d, 0x6a, 0x0f, 0x9c, 0x5e, 0x45, 0x50, 0x79, 0x50, 0x30, 0xe1,
	0xcc, 0x18, 0xd8, 0xac, 0x72, 0x74, 0x70, 0x7a, 0x5c, 0xdc, 0xde, 0xbd, 0x7f, 0xaf, 0xbc, 0x53,
	0xde, 0xdd, 0x29, 0xef, 0x16, 0xca, 0xe5, 0x8a, 0xff, 0xb7, 0xfd, 0xdf, 0xd6, 0xeb, 0x8f, 0x9a,
	0xd2, 0x4c, 0x85, 0x0b, 0x0f, 0x58, 0x83, 0xa9, 0xaf, 0x14, 0x94, 0x15, 0x84, 0x00, 0xff, 0xbc,
	0xd0, 0xcf, 0xa3, 0xd0, 0xcf, 0xc1, 0xb7, 0xfd, 0x40, 0x04, 0x43, 0xe9, 0x29, 0x43, 0x30, 0x0b,
	0x88, 0x30, 0xfc, 0x4b, 0x7c, 0x40, 0x44, 0x0e, 0x50, 0x6d, 0x0e, 0x10, 0x61, 0x80, 0x97, 0xe2,
	0x03, 0x22, 0x92, 0x80, 0x6a, 0x21, 0xa0, 0x81, 0x6b, 0x4e, 0x75, 0xd0, 0x8a, 0x24, 0x20, 0x41,
	0x25, 0x0a, 0xa0, 0x70, 0xe1, 0xa4, 0x83, 0x04, 0x21, 0xc0, 0x49, 0x49, 0x40, 0xa2, 0x4c, 0x14,
	0x40, 0x53, 0x86, 0xe6, 0x00, 0x11, 0x86, 0x51, 0x7c, 0x40, 0x44, 0x0e, 0x50, 0x6d, 0x0e, 0x10,
	0xef, 0xa0, 0x54, 0x7c, 0x40, 0x44, 0x12, 0x10, 0xef, 0xa0, 0x75, 0x94, 0xb0, 0xcc, 0x3e, 0x4e,
	0x17, 0x12, 0xc5, 0x44, 0x75, 0x79, 0x34, 0xd4, 0x12, 0xf5, 0xa3, 0x7e, 0x93, 0xc7, 0xd4, 0xff,
	0x11, 0xf2, 0x9b, 0x8d, 0x7a, 0x2d, 0xcb, 0xc4, 0x99, 0x82, 0x52, 0x4c, 0x54, 0x33, 0xa3, 0xa1,
	0x96, 0x3c, 0x0c, 0xa2, 0xf5, 0xa3, 0x66, 0x32, 0x4c, 0xa8, 0x9b, 0xea, 0x3f, 0x28, 0x3d, 0xce,
	0xee, 0x19, 0x0e, 0xe0, 0xac, 0xff, 0xad, 0x4b, 0x85, 0xb1, 0x13, 0xc3, 0x01, 0x2e, 0x18, 0xd4,
	0xf6, 0x05, 0x57, 0xaf, 0x05, 0x9f, 0x04, 0x51, 0x2e, 0x18, 0x26, 0x04, 0x82, 0xe3, 0x6c, 0x5f,
	0x70, 0x2d, 0x10, 0x0c, 0x63, 0xbe, 0x20, 0x3f, 0x5d, 0x13, 0x6c, 0xb8, 0x6e, 0xff, 0x5f, 0x25,
	0x4f, 0x57, 0x50, 0x89, 0x72, 0xba, 0xe1, 0xc2, 0x49, 0xfb, 0x0b, 0x42, 0x80, 0x55, 0xc9, 0xd3,
	0x15, 0x65, 0xa2, 0x9c, 0xee, 0x94, 0xa1, 0x39, 0x40, 0x84, 0xe1, 0xdf, 0xe2, 0x03, 0x22, 0x72,
	0x80, 0x6a, 0x73, 0x80, 0x78, 0xfb, 0xff, 0x1e, 0x1f, 0x10, 0x91, 0x04, 0x34, 0xfe, 0x80, 0xc2,
	0x73, 0xd7, 0xf2, 0x26, 0x80, 0xfe, 0x90, 0x04, 0x24, 0xa8, 0x44, 0x01, 0x14, 0x2e, 0x9c, 0x00,
	0x12, 0x84, 0x00, 0xff, 0x29, 0x09, 0x48, 0x94, 0x89, 0x02, 0x68, 0xca, 0xd0, 0x1c, 0x20, 0x9b,
	0xe1, 0xbf, 0xe2, 0x03, 0xb2, 0xe5, 0x00, 0x35, 0xe6, 0x00, 0xf1, 0x11, 0xc3, 0xf1, 0x01, 0xd9,
	0x92, 0x80, 0xf8, 0x88, 0xbd, 0x51, 0xd0, 0x6a, 0x87, 0x3a, 0xee, 0xf4, 0x57, 0x68, 0x7d, 0xa1,
	0xa5, 0x93, 0xd0, 0x52, 0x55, 0xfc, 0x55, 0x20, 0xea, 0x44, 0xf0, 0x94, 0x99, 0x2c, 0xf5, 0x31,
	0xbd, 0x55, 0xd0, 0xda, 0x8c, 0x18, 0xe0, 0xdc, 0x42, 0x57, 0x8f, 0x43, 0x57, 0x87, 0xdf, 0x73,
	0x15, 0x05, 0x55, 0x56, 0xb0, 0x75, 0x03, 0x2c, 0xc2, 0xf0, 0xc6, 0x6d, 0xc0, 0x22, 0xb2, 0xb0,
	0x6a, 0x37, 0xc0, 0xe2, 0x63, 0xb7, 0x79, 0x1b, 0xb0, 0x88, 0x34, 0x2c, 0x3e, 0x7a, 0x2e, 0xca,
	0x30, 0xcf, 0x30, 0xa1, 0xc5, 0xef, 0x2a, 0x9c, 0xd4, 0xdf, 0x0b, 0x3d, 0x95, 0x43, 0x4f, 0xff,
	0xfe, 0xf8, 0x74, 0xf9, 0x25, 0xb8, 0x42, 0x8d, 0xa9, 0x1e, 0xca, 0x0a, 0x15, 0x01, 0xe7, 0xef,
	0xa0, 0x64, 0x7a, 0xaa, 0xe4, 0xec, 0x2e, 0x6d, 0x86, 0xb5, 0x3b, 0xdd, 0x65, 0x63, 0x76, 0x97,
	0x7c, 0x32, 0x0a, 0x77, 0xba, 0xcb, 0x06, 0x83, 0xea, 0xf1, 0xd5, 0x28, 0xaf, 0x7c, 0x18, 0xe5,
	0x95, 0x4f, 0xa3, 0xbc, 0xf2, 0xfe, 0x73, 0x5e, 0x79, 0xb6, 0x4f, 0x2c, 0x66, 0x1b, 0xed, 0x52,
	0xdf, 0xb2, 0xcf, 0x3d, 0x6a, 0x02, 0xbf, 0x79, 0x96, 0xd8, 0xa5, 0x4e, 0xa8, 0x6d, 0xf4, 0x88,
	0x4e, 0xa8, 0xdb, 0x05, 0x4f, 0x17, 0xef, 0xb8, 0xed, 0x25, 0xdf, 0xda, 0xfe, 0xd7, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x49, 0xa8, 0xaa, 0x00, 0xfc, 0x0e, 0x00, 0x00,
}

func (m *BaseWhere) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BaseWhere) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BaseWhere) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.TradeTimeLte != nil {
		n1, err1 := github_com_gogo_protobuf_types.StdTimeMarshalTo(*m.TradeTimeLte, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(*m.TradeTimeLte):])
		if err1 != nil {
			return 0, err1
		}
		i -= n1
		i = encodeVarintBaseWhere(dAtA, i, uint64(n1))
		i--
		dAtA[i] = 0x2
		i--
		dAtA[i] = 0x82
	}
	if m.TradeTimeLt != nil {
		n2, err2 := github_com_gogo_protobuf_types.StdTimeMarshalTo(*m.TradeTimeLt, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(*m.TradeTimeLt):])
		if err2 != nil {
			return 0, err2
		}
		i -= n2
		i = encodeVarintBaseWhere(dAtA, i, uint64(n2))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xfa
	}
	if m.TradeTimeGte != nil {
		n3, err3 := github_com_gogo_protobuf_types.StdTimeMarshalTo(*m.TradeTimeGte, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(*m.TradeTimeGte):])
		if err3 != nil {
			return 0, err3
		}
		i -= n3
		i = encodeVarintBaseWhere(dAtA, i, uint64(n3))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xf2
	}
	if m.TradeTimeGt != nil {
		n4, err4 := github_com_gogo_protobuf_types.StdTimeMarshalTo(*m.TradeTimeGt, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(*m.TradeTimeGt):])
		if err4 != nil {
			return 0, err4
		}
		i -= n4
		i = encodeVarintBaseWhere(dAtA, i, uint64(n4))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xea
	}
	if m.CompletedAtGte != nil {
		n5, err5 := github_com_gogo_protobuf_types.StdTimeMarshalTo(*m.CompletedAtGte, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(*m.CompletedAtGte):])
		if err5 != nil {
			return 0, err5
		}
		i -= n5
		i = encodeVarintBaseWhere(dAtA, i, uint64(n5))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xe2
	}
	if m.CompletedAtGt != nil {
		n6, err6 := github_com_gogo_protobuf_types.StdTimeMarshalTo(*m.CompletedAtGt, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(*m.CompletedAtGt):])
		if err6 != nil {
			return 0, err6
		}
		i -= n6
		i = encodeVarintBaseWhere(dAtA, i, uint64(n6))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xda
	}
	if m.CompletedAtLte != nil {
		n7, err7 := github_com_gogo_protobuf_types.StdTimeMarshalTo(*m.CompletedAtLte, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(*m.CompletedAtLte):])
		if err7 != nil {
			return 0, err7
		}
		i -= n7
		i = encodeVarintBaseWhere(dAtA, i, uint64(n7))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xd2
	}
	if m.CompletedAtLt != nil {
		n8, err8 := github_com_gogo_protobuf_types.StdTimeMarshalTo(*m.CompletedAtLt, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(*m.CompletedAtLt):])
		if err8 != nil {
			return 0, err8
		}
		i -= n8
		i = encodeVarintBaseWhere(dAtA, i, uint64(n8))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xca
	}
	if m.ExpiredAtLte != nil {
		n9, err9 := github_com_gogo_protobuf_types.StdTimeMarshalTo(*m.ExpiredAtLte, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(*m.ExpiredAtLte):])
		if err9 != nil {
			return 0, err9
		}
		i -= n9
		i = encodeVarintBaseWhere(dAtA, i, uint64(n9))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xc2
	}
	if m.ExpiredAtLt != nil {
		n10, err10 := github_com_gogo_protobuf_types.StdTimeMarshalTo(*m.ExpiredAtLt, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(*m.ExpiredAtLt):])
		if err10 != nil {
			return 0, err10
		}
		i -= n10
		i = encodeVarintBaseWhere(dAtA, i, uint64(n10))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xba
	}
	if m.ExpiredAtGte != nil {
		n11, err11 := github_com_gogo_protobuf_types.StdTimeMarshalTo(*m.ExpiredAtGte, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(*m.ExpiredAtGte):])
		if err11 != nil {
			return 0, err11
		}
		i -= n11
		i = encodeVarintBaseWhere(dAtA, i, uint64(n11))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xb2
	}
	if m.ExpiredAtGt != nil {
		n12, err12 := github_com_gogo_protobuf_types.StdTimeMarshalTo(*m.ExpiredAtGt, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(*m.ExpiredAtGt):])
		if err12 != nil {
			return 0, err12
		}
		i -= n12
		i = encodeVarintBaseWhere(dAtA, i, uint64(n12))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xaa
	}
	if m.DeletedAtGte != nil {
		n13, err13 := github_com_gogo_protobuf_types.StdTimeMarshalTo(*m.DeletedAtGte, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(*m.DeletedAtGte):])
		if err13 != nil {
			return 0, err13
		}
		i -= n13
		i = encodeVarintBaseWhere(dAtA, i, uint64(n13))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xa2
	}
	if m.DeletedAtGt != nil {
		n14, err14 := github_com_gogo_protobuf_types.StdTimeMarshalTo(*m.DeletedAtGt, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(*m.DeletedAtGt):])
		if err14 != nil {
			return 0, err14
		}
		i -= n14
		i = encodeVarintBaseWhere(dAtA, i, uint64(n14))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x9a
	}
	if m.DeletedAtLte != nil {
		n15, err15 := github_com_gogo_protobuf_types.StdTimeMarshalTo(*m.DeletedAtLte, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(*m.DeletedAtLte):])
		if err15 != nil {
			return 0, err15
		}
		i -= n15
		i = encodeVarintBaseWhere(dAtA, i, uint64(n15))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x92
	}
	if m.DeletedAtLt != nil {
		n16, err16 := github_com_gogo_protobuf_types.StdTimeMarshalTo(*m.DeletedAtLt, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(*m.DeletedAtLt):])
		if err16 != nil {
			return 0, err16
		}
		i -= n16
		i = encodeVarintBaseWhere(dAtA, i, uint64(n16))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x8a
	}
	if len(m.UpdaterName) > 0 {
		i -= len(m.UpdaterName)
		copy(dAtA[i:], m.UpdaterName)
		i = encodeVarintBaseWhere(dAtA, i, uint64(len(m.UpdaterName)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x82
	}
	if m.UpdaterID != 0 {
		i = encodeVarintBaseWhere(dAtA, i, uint64(m.UpdaterID))
		i--
		dAtA[i] = 0x78
	}
	if len(m.CreatorName) > 0 {
		i -= len(m.CreatorName)
		copy(dAtA[i:], m.CreatorName)
		i = encodeVarintBaseWhere(dAtA, i, uint64(len(m.CreatorName)))
		i--
		dAtA[i] = 0x72
	}
	if m.CreatorID != 0 {
		i = encodeVarintBaseWhere(dAtA, i, uint64(m.CreatorID))
		i--
		dAtA[i] = 0x68
	}
	if len(m.IDs) > 0 {
		dAtA18 := make([]byte, len(m.IDs)*10)
		var j17 int
		for _, num1 := range m.IDs {
			num := uint64(num1)
			for num >= 1<<7 {
				dAtA18[j17] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j17++
			}
			dAtA18[j17] = uint8(num)
			j17++
		}
		i -= j17
		copy(dAtA[i:], dAtA18[:j17])
		i = encodeVarintBaseWhere(dAtA, i, uint64(j17))
		i--
		dAtA[i] = 0x62
	}
	if m.UpdatedAtGte != nil {
		n19, err19 := github_com_gogo_protobuf_types.StdTimeMarshalTo(*m.UpdatedAtGte, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(*m.UpdatedAtGte):])
		if err19 != nil {
			return 0, err19
		}
		i -= n19
		i = encodeVarintBaseWhere(dAtA, i, uint64(n19))
		i--
		dAtA[i] = 0x5a
	}
	if m.UpdatedAtGt != nil {
		n20, err20 := github_com_gogo_protobuf_types.StdTimeMarshalTo(*m.UpdatedAtGt, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(*m.UpdatedAtGt):])
		if err20 != nil {
			return 0, err20
		}
		i -= n20
		i = encodeVarintBaseWhere(dAtA, i, uint64(n20))
		i--
		dAtA[i] = 0x52
	}
	if m.UpdatedAtLte != nil {
		n21, err21 := github_com_gogo_protobuf_types.StdTimeMarshalTo(*m.UpdatedAtLte, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(*m.UpdatedAtLte):])
		if err21 != nil {
			return 0, err21
		}
		i -= n21
		i = encodeVarintBaseWhere(dAtA, i, uint64(n21))
		i--
		dAtA[i] = 0x4a
	}
	if m.UpdatedAtLt != nil {
		n22, err22 := github_com_gogo_protobuf_types.StdTimeMarshalTo(*m.UpdatedAtLt, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(*m.UpdatedAtLt):])
		if err22 != nil {
			return 0, err22
		}
		i -= n22
		i = encodeVarintBaseWhere(dAtA, i, uint64(n22))
		i--
		dAtA[i] = 0x42
	}
	if m.CreatedAtGte != nil {
		n23, err23 := github_com_gogo_protobuf_types.StdTimeMarshalTo(*m.CreatedAtGte, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(*m.CreatedAtGte):])
		if err23 != nil {
			return 0, err23
		}
		i -= n23
		i = encodeVarintBaseWhere(dAtA, i, uint64(n23))
		i--
		dAtA[i] = 0x32
	}
	if m.CreatedAtGt != nil {
		n24, err24 := github_com_gogo_protobuf_types.StdTimeMarshalTo(*m.CreatedAtGt, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(*m.CreatedAtGt):])
		if err24 != nil {
			return 0, err24
		}
		i -= n24
		i = encodeVarintBaseWhere(dAtA, i, uint64(n24))
		i--
		dAtA[i] = 0x2a
	}
	if m.CreatedAtLte != nil {
		n25, err25 := github_com_gogo_protobuf_types.StdTimeMarshalTo(*m.CreatedAtLte, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(*m.CreatedAtLte):])
		if err25 != nil {
			return 0, err25
		}
		i -= n25
		i = encodeVarintBaseWhere(dAtA, i, uint64(n25))
		i--
		dAtA[i] = 0x22
	}
	if m.CreatedAtLt != nil {
		n26, err26 := github_com_gogo_protobuf_types.StdTimeMarshalTo(*m.CreatedAtLt, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(*m.CreatedAtLt):])
		if err26 != nil {
			return 0, err26
		}
		i -= n26
		i = encodeVarintBaseWhere(dAtA, i, uint64(n26))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Keyword) > 0 {
		i -= len(m.Keyword)
		copy(dAtA[i:], m.Keyword)
		i = encodeVarintBaseWhere(dAtA, i, uint64(len(m.Keyword)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.SearchIn) > 0 {
		i -= len(m.SearchIn)
		copy(dAtA[i:], m.SearchIn)
		i = encodeVarintBaseWhere(dAtA, i, uint64(len(m.SearchIn)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintBaseWhere(dAtA []byte, offset int, v uint64) int {
	offset -= sovBaseWhere(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *BaseWhere) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.SearchIn)
	if l > 0 {
		n += 1 + l + sovBaseWhere(uint64(l))
	}
	l = len(m.Keyword)
	if l > 0 {
		n += 1 + l + sovBaseWhere(uint64(l))
	}
	if m.CreatedAtLt != nil {
		l = github_com_gogo_protobuf_types.SizeOfStdTime(*m.CreatedAtLt)
		n += 1 + l + sovBaseWhere(uint64(l))
	}
	if m.CreatedAtLte != nil {
		l = github_com_gogo_protobuf_types.SizeOfStdTime(*m.CreatedAtLte)
		n += 1 + l + sovBaseWhere(uint64(l))
	}
	if m.CreatedAtGt != nil {
		l = github_com_gogo_protobuf_types.SizeOfStdTime(*m.CreatedAtGt)
		n += 1 + l + sovBaseWhere(uint64(l))
	}
	if m.CreatedAtGte != nil {
		l = github_com_gogo_protobuf_types.SizeOfStdTime(*m.CreatedAtGte)
		n += 1 + l + sovBaseWhere(uint64(l))
	}
	if m.UpdatedAtLt != nil {
		l = github_com_gogo_protobuf_types.SizeOfStdTime(*m.UpdatedAtLt)
		n += 1 + l + sovBaseWhere(uint64(l))
	}
	if m.UpdatedAtLte != nil {
		l = github_com_gogo_protobuf_types.SizeOfStdTime(*m.UpdatedAtLte)
		n += 1 + l + sovBaseWhere(uint64(l))
	}
	if m.UpdatedAtGt != nil {
		l = github_com_gogo_protobuf_types.SizeOfStdTime(*m.UpdatedAtGt)
		n += 1 + l + sovBaseWhere(uint64(l))
	}
	if m.UpdatedAtGte != nil {
		l = github_com_gogo_protobuf_types.SizeOfStdTime(*m.UpdatedAtGte)
		n += 1 + l + sovBaseWhere(uint64(l))
	}
	if len(m.IDs) > 0 {
		l = 0
		for _, e := range m.IDs {
			l += sovBaseWhere(uint64(e))
		}
		n += 1 + sovBaseWhere(uint64(l)) + l
	}
	if m.CreatorID != 0 {
		n += 1 + sovBaseWhere(uint64(m.CreatorID))
	}
	l = len(m.CreatorName)
	if l > 0 {
		n += 1 + l + sovBaseWhere(uint64(l))
	}
	if m.UpdaterID != 0 {
		n += 1 + sovBaseWhere(uint64(m.UpdaterID))
	}
	l = len(m.UpdaterName)
	if l > 0 {
		n += 2 + l + sovBaseWhere(uint64(l))
	}
	if m.DeletedAtLt != nil {
		l = github_com_gogo_protobuf_types.SizeOfStdTime(*m.DeletedAtLt)
		n += 2 + l + sovBaseWhere(uint64(l))
	}
	if m.DeletedAtLte != nil {
		l = github_com_gogo_protobuf_types.SizeOfStdTime(*m.DeletedAtLte)
		n += 2 + l + sovBaseWhere(uint64(l))
	}
	if m.DeletedAtGt != nil {
		l = github_com_gogo_protobuf_types.SizeOfStdTime(*m.DeletedAtGt)
		n += 2 + l + sovBaseWhere(uint64(l))
	}
	if m.DeletedAtGte != nil {
		l = github_com_gogo_protobuf_types.SizeOfStdTime(*m.DeletedAtGte)
		n += 2 + l + sovBaseWhere(uint64(l))
	}
	if m.ExpiredAtGt != nil {
		l = github_com_gogo_protobuf_types.SizeOfStdTime(*m.ExpiredAtGt)
		n += 2 + l + sovBaseWhere(uint64(l))
	}
	if m.ExpiredAtGte != nil {
		l = github_com_gogo_protobuf_types.SizeOfStdTime(*m.ExpiredAtGte)
		n += 2 + l + sovBaseWhere(uint64(l))
	}
	if m.ExpiredAtLt != nil {
		l = github_com_gogo_protobuf_types.SizeOfStdTime(*m.ExpiredAtLt)
		n += 2 + l + sovBaseWhere(uint64(l))
	}
	if m.ExpiredAtLte != nil {
		l = github_com_gogo_protobuf_types.SizeOfStdTime(*m.ExpiredAtLte)
		n += 2 + l + sovBaseWhere(uint64(l))
	}
	if m.CompletedAtLt != nil {
		l = github_com_gogo_protobuf_types.SizeOfStdTime(*m.CompletedAtLt)
		n += 2 + l + sovBaseWhere(uint64(l))
	}
	if m.CompletedAtLte != nil {
		l = github_com_gogo_protobuf_types.SizeOfStdTime(*m.CompletedAtLte)
		n += 2 + l + sovBaseWhere(uint64(l))
	}
	if m.CompletedAtGt != nil {
		l = github_com_gogo_protobuf_types.SizeOfStdTime(*m.CompletedAtGt)
		n += 2 + l + sovBaseWhere(uint64(l))
	}
	if m.CompletedAtGte != nil {
		l = github_com_gogo_protobuf_types.SizeOfStdTime(*m.CompletedAtGte)
		n += 2 + l + sovBaseWhere(uint64(l))
	}
	if m.TradeTimeGt != nil {
		l = github_com_gogo_protobuf_types.SizeOfStdTime(*m.TradeTimeGt)
		n += 2 + l + sovBaseWhere(uint64(l))
	}
	if m.TradeTimeGte != nil {
		l = github_com_gogo_protobuf_types.SizeOfStdTime(*m.TradeTimeGte)
		n += 2 + l + sovBaseWhere(uint64(l))
	}
	if m.TradeTimeLt != nil {
		l = github_com_gogo_protobuf_types.SizeOfStdTime(*m.TradeTimeLt)
		n += 2 + l + sovBaseWhere(uint64(l))
	}
	if m.TradeTimeLte != nil {
		l = github_com_gogo_protobuf_types.SizeOfStdTime(*m.TradeTimeLte)
		n += 2 + l + sovBaseWhere(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovBaseWhere(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozBaseWhere(x uint64) (n int) {
	return sovBaseWhere(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *BaseWhere) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBaseWhere
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BaseWhere: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BaseWhere: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SearchIn", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBaseWhere
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBaseWhere
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBaseWhere
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SearchIn = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Keyword", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBaseWhere
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBaseWhere
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBaseWhere
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Keyword = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAtLt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBaseWhere
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBaseWhere
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBaseWhere
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.CreatedAtLt == nil {
				m.CreatedAtLt = new(time.Time)
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(m.CreatedAtLt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAtLte", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBaseWhere
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBaseWhere
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBaseWhere
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.CreatedAtLte == nil {
				m.CreatedAtLte = new(time.Time)
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(m.CreatedAtLte, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAtGt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBaseWhere
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBaseWhere
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBaseWhere
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.CreatedAtGt == nil {
				m.CreatedAtGt = new(time.Time)
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(m.CreatedAtGt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAtGte", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBaseWhere
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBaseWhere
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBaseWhere
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.CreatedAtGte == nil {
				m.CreatedAtGte = new(time.Time)
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(m.CreatedAtGte, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdatedAtLt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBaseWhere
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBaseWhere
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBaseWhere
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.UpdatedAtLt == nil {
				m.UpdatedAtLt = new(time.Time)
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(m.UpdatedAtLt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdatedAtLte", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBaseWhere
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBaseWhere
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBaseWhere
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.UpdatedAtLte == nil {
				m.UpdatedAtLte = new(time.Time)
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(m.UpdatedAtLte, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdatedAtGt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBaseWhere
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBaseWhere
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBaseWhere
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.UpdatedAtGt == nil {
				m.UpdatedAtGt = new(time.Time)
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(m.UpdatedAtGt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdatedAtGte", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBaseWhere
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBaseWhere
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBaseWhere
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.UpdatedAtGte == nil {
				m.UpdatedAtGte = new(time.Time)
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(m.UpdatedAtGte, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 12:
			if wireType == 0 {
				var v int64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowBaseWhere
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= int64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.IDs = append(m.IDs, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowBaseWhere
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthBaseWhere
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthBaseWhere
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.IDs) == 0 {
					m.IDs = make([]int64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v int64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowBaseWhere
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= int64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.IDs = append(m.IDs, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field IDs", wireType)
			}
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatorID", wireType)
			}
			m.CreatorID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBaseWhere
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatorID |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatorName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBaseWhere
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBaseWhere
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBaseWhere
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CreatorName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 15:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdaterID", wireType)
			}
			m.UpdaterID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBaseWhere
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UpdaterID |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 16:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdaterName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBaseWhere
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBaseWhere
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBaseWhere
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UpdaterName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 17:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeletedAtLt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBaseWhere
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBaseWhere
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBaseWhere
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.DeletedAtLt == nil {
				m.DeletedAtLt = new(time.Time)
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(m.DeletedAtLt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 18:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeletedAtLte", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBaseWhere
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBaseWhere
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBaseWhere
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.DeletedAtLte == nil {
				m.DeletedAtLte = new(time.Time)
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(m.DeletedAtLte, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 19:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeletedAtGt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBaseWhere
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBaseWhere
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBaseWhere
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.DeletedAtGt == nil {
				m.DeletedAtGt = new(time.Time)
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(m.DeletedAtGt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 20:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeletedAtGte", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBaseWhere
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBaseWhere
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBaseWhere
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.DeletedAtGte == nil {
				m.DeletedAtGte = new(time.Time)
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(m.DeletedAtGte, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 21:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpiredAtGt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBaseWhere
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBaseWhere
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBaseWhere
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ExpiredAtGt == nil {
				m.ExpiredAtGt = new(time.Time)
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(m.ExpiredAtGt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 22:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpiredAtGte", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBaseWhere
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBaseWhere
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBaseWhere
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ExpiredAtGte == nil {
				m.ExpiredAtGte = new(time.Time)
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(m.ExpiredAtGte, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 23:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpiredAtLt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBaseWhere
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBaseWhere
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBaseWhere
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ExpiredAtLt == nil {
				m.ExpiredAtLt = new(time.Time)
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(m.ExpiredAtLt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 24:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpiredAtLte", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBaseWhere
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBaseWhere
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBaseWhere
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ExpiredAtLte == nil {
				m.ExpiredAtLte = new(time.Time)
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(m.ExpiredAtLte, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 25:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CompletedAtLt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBaseWhere
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBaseWhere
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBaseWhere
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.CompletedAtLt == nil {
				m.CompletedAtLt = new(time.Time)
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(m.CompletedAtLt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 26:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CompletedAtLte", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBaseWhere
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBaseWhere
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBaseWhere
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.CompletedAtLte == nil {
				m.CompletedAtLte = new(time.Time)
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(m.CompletedAtLte, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 27:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CompletedAtGt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBaseWhere
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBaseWhere
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBaseWhere
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.CompletedAtGt == nil {
				m.CompletedAtGt = new(time.Time)
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(m.CompletedAtGt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 28:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CompletedAtGte", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBaseWhere
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBaseWhere
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBaseWhere
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.CompletedAtGte == nil {
				m.CompletedAtGte = new(time.Time)
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(m.CompletedAtGte, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 29:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TradeTimeGt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBaseWhere
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBaseWhere
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBaseWhere
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.TradeTimeGt == nil {
				m.TradeTimeGt = new(time.Time)
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(m.TradeTimeGt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 30:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TradeTimeGte", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBaseWhere
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBaseWhere
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBaseWhere
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.TradeTimeGte == nil {
				m.TradeTimeGte = new(time.Time)
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(m.TradeTimeGte, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 31:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TradeTimeLt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBaseWhere
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBaseWhere
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBaseWhere
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.TradeTimeLt == nil {
				m.TradeTimeLt = new(time.Time)
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(m.TradeTimeLt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 32:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TradeTimeLte", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBaseWhere
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBaseWhere
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBaseWhere
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.TradeTimeLte == nil {
				m.TradeTimeLte = new(time.Time)
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(m.TradeTimeLte, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipBaseWhere(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthBaseWhere
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthBaseWhere
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipBaseWhere(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowBaseWhere
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBaseWhere
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBaseWhere
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthBaseWhere
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupBaseWhere
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthBaseWhere
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthBaseWhere        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowBaseWhere          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupBaseWhere = fmt.Errorf("proto: unexpected end of group")
)
